# (C) Copyright 2024 WeatherGenerator contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

iasi_pc :
  type : obs
  filenames : ['observations-od-ai-0001-2011-2023-iasi-pc-bufr-v1.zarr']
  loss_weight : 1.0
  token_size : 32
  max_num_targets: -1
  embed :
    net : transformer
    num_tokens : 1
    num_heads : 2
    dim_embed : 128
    num_blocks : 2
  embed_target_coords :
    net : linear
    dim_embed : 128
  target_readout :
    type : 'obs_value'
    num_layers : 1
    num_heads : 4
  pred_head :
    ens_size : 1
    num_layers : 1
