[[index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true


#[sources]

#torch = [
#  { url = "https://download.pytorch.org/whl/cpu" },
#]

#flash-attn = [
#  { index = "pytorch-cpu"},
#]
