#optional: if commented out all is taken care of by the default settings
# NB. global options apply to all run_ids 
#global_plotting_options:
#  image_format : "png" #options: "png", "pdf", "svg", "eps", "jpg" ..
#  dpi_val : 300
#  ERA5:
#    marker_size: 2
#    scale_marker_size: 1
#    marker: "o"
#    # alpha: 0.5
#    2t: 
#      vmin: 250
#      vmax: 300
#    10u:
#      vmin: -40
#      vmax: 40

evaluation:
  metrics  : ["rmse"]
  regions: ["global"]
  summary_plots : true
  summary_dir: "./plots/"
  plot_ensemble: false #supported: false, "std", "minmax", "members"
  print_summary: true #print out score values on screen. it can be verbose
  log_scale: false
  add_grid: false
  score_cards: True
  spatial_dims:
    lat_dims: [y, lat, latitude]
    lon_dims: [x, lon, longitude]


run_ids :
  lydspjuc:
    label: "pretrained model, MoE, no transform"
    results_base_dir : "./results/"
    epoch: 0
    rank: 0
    streams:
      ERA5:
        channels: ["2t", "10v"] # "z_500", "t_850", "u_850", "v_850", "q_850", ]
        evaluation:
          forecast_step: "all"
          sample: "all"
          ensemble: "all" #supported: "all", "mean", [0,1,2]
        plotting:
          sample: "all"
          forecast_step: "all"
        #   # ensemble: [0,2,5] #supported: "all", "mean", [0,1,2]
          plot_maps: true
          plot_histograms: true
          plot_animations: true
    