#optional: if commented out all is taken care of by the default settings
# NB. global options apply to all run_ids 
#global_plotting_options:
#  image_format : "png" #options: "png", "pdf", "svg", "eps", "jpg" ..
#  dpi_val : 300
#  ERA5:
#    marker_size: 2
#    scale_marker_size: 1
#    marker: "o"
#    # alpha: 0.5
#    2t: 
#      vmin: 250
#      vmax: 300
#    10u:
#      vmin: -40
#      vmax: 40

evaluation:
  metrics  : ["rmse", "mae"] #options: "l1", "l2", "froct", "bias", "rmse", "mae" etc..
  regions: ["global", "nhem"] #options: "global", "nhem", "shem", "tropics"
  summary_plots : true
  plot_ensemble: false, #"members" #options: false, "std", "minmax", "members"
  summary_dir: "./plots/"
  print_summary: false #print out score values on screen. it can be verbose
  log_scale: false
  add_grid: false
  score_cards: true
  bar_plots: true
run_ids :
  test_small1_60289:
    label: "pretrained model ar40mckx"
    results_base_dir : "./results/"
    epoch: 0
    rank: 0
    streams:
      ERA5:
        channels: [ "t_850"]
        evaluation:
          forecast_step: "all"
          sample: "all"
          #ensemble: "all" #supported: "all", "mean", [0,1,2]
        plotting:
          sample: [0]
          forecast_step: [1]
          ensemble: [0]
          # ensemble: [0,2,5] #supported: "all", "mean", [0,1,2]
          plot_maps: false
          plot_histograms: false
          plot_animations: false
