# (C) Copyright 2024 WeatherGenerator contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

CAMSEAC4 :
  type : camseac4
  filenames : ['cams_eac4_2003_2024.zarr']
  source : [
      # Surface variables
      'pm1', 'pm2p5', 'pm10',
      'tc_co', 'tc_no', 'tc_no2', 'tc_o3', 'tc_so2',

      # Ozone (o3)
      'go3_1000', 'go3_925', 'go3_850', 'go3_700', 'go3_600', 'go3_500',
      'go3_400', 'go3_300', 'go3_250', 'go3_200', 'go3_150', 'go3_100', 'go3_50',

      # Sulfur dioxide (so2)
      'so2_1000', 'so2_925', 'so2_850', 'so2_700', 'so2_600', 'so2_500',
      'so2_400', 'so2_300', 'so2_250', 'so2_200', 'so2_150', 'so2_100', 'so2_50',
  ]
  target : [
      # Surface variables
      'pm1', 'pm2p5', 'pm10',
      'tc_co', 'tc_no', 'tc_no2', 'tc_o3', 'tc_so2',

      # Ozone (o3)
      'go3_1000', 'go3_925', 'go3_850', 'go3_700', 'go3_600', 'go3_500',
      'go3_400', 'go3_300', 'go3_250', 'go3_200', 'go3_150', 'go3_100', 'go3_50',

      # Sulfur dioxide (so2)
      'so2_1000', 'so2_925', 'so2_850', 'so2_700', 'so2_600', 'so2_500',
      'so2_400', 'so2_300', 'so2_250', 'so2_200', 'so2_150', 'so2_100', 'so2_50',
  ]
  # source_exclude : []
  # target_exclude : []
  variables: [
      # Surface variables
      'pm1', 'pm2p5', 'pm10',
      'tc_co', 'tc_no', 'tc_no2', 'tc_o3', 'tc_so2',

      # Ozone (o3)
      'go3_1000', 'go3_925', 'go3_850', 'go3_700', 'go3_600', 'go3_500',
      'go3_400', 'go3_300', 'go3_250', 'go3_200', 'go3_150', 'go3_100', 'go3_50',

      # Sulfur dioxide (so2)
      'so2_1000', 'so2_925', 'so2_850', 'so2_700', 'so2_600', 'so2_500',
      'so2_400', 'so2_300', 'so2_250', 'so2_200', 'so2_150', 'so2_100', 'so2_50',
  ]
  loss_weight : 1.
  masking_rate : 0.6
  masking_rate_none : 0.05
  token_size : 32
  tokenize_spacetime : True
  embed : 
    net : transformer
    num_tokens : 1
    num_heads : 8
    dim_embed : 512
    num_blocks : 4
  embed_target_coords :
    net : linear
    dim_embed : 512 
  target_readout :
    type : 'obs_value'  # token or obs_value
    num_layers : 2
    num_heads : 4
    # sampling_rate : 0.2
  pred_head :
    ens_size : 1
    num_layers : 1