# (C) Copyright 2024 WeatherGenerator contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

CAMSEAC4 :
  type : camseac4
  filenames : ['cams_eac4_2017_2022.zarr']
  source : [
      # Surface variables
      '2t', 'u10', 'v10', 'msl', 'pm1', 'pm2p5', 'pm10',
      'tc_co', 'tc_no', 'tc_no2', 'tc_o3', 'tc_so2',

      # Specific humidity (q)
      'q_1000',  'q_700', 'q_400',
      'q_250',  'q_150',  'q_50',

      # Temperature (t)
      't_1000',  't_700', 't_400',
      't_250',  't_150',  't_50',

      # U wind (u)
      'u_1000',  'u_700', 'u_400',
      'u_250',  'u_150',  'u_50',

      # V wind (v)
      'v_1000',  'v_700', 'v_400',
      'v_250',  'v_150',  'v_50',

      # Ozone (o3)
      'o3_1000',  'o3_700', 'o3_400',
      'o3_250',  'o3_150',  'o3_50',

      # Sulfur dioxide (so2)
      'so2_1000',  'so2_700', 'so2_400',
      'so2_250',  'so2_150',  'so2_50',

      # Geopotential height (z)
      'z_1000',  'z_700', 'z_400',
      'z_250',  'z_150',  'z_50',
  ]
  target : [
      # Surface variables
      '2t', 'u10', 'v10', 'msl', 'pm1', 'pm2p5', 'pm10',
      'tc_co', 'tc_no', 'tc_no2', 'tc_o3', 'tc_so2',

      # Specific humidity (q)
      'q_1000',  'q_700', 'q_400',
      'q_250',  'q_150',  'q_50',

      # Temperature (t)
      't_1000',  't_700', 't_400',
      't_250',  't_150',  't_50',

      # U wind (u)
      'u_1000',  'u_700', 'u_400',
      'u_250',  'u_150',  'u_50',

      # V wind (v)
      'v_1000',  'v_700', 'v_400',
      'v_250',  'v_150',  'v_50',

      # Ozone (o3)
      'o3_1000',  'o3_700', 'o3_400',
      'o3_250',  'o3_150',  'o3_50',

      # Sulfur dioxide (so2)
      'so2_1000',  'so2_700', 'so2_400',
      'so2_250',  'so2_150',  'so2_50',

      # Geopotential height (z)
      'z_1000',  'z_700', 'z_400',
      'z_250',  'z_150',  'z_50',

  ]
  # source_exclude : []
  # target_exclude : []
  variables: [
      # Surface variables
      '2t', 'u10', 'v10', 'msl', 'pm1', 'pm2p5', 'pm10',
      'tc_co', 'tc_no', 'tc_no2', 'tc_o3', 'tc_so2',

      # Specific humidity (q)
      'q_1000', 'q_925', 'q_850', 'q_700', 'q_600', 'q_500',
      'q_400', 'q_300', 'q_250', 'q_200', 'q_150', 'q_100', 'q_50',

      # Temperature (t)
      't_1000', 't_925', 't_850', 't_700', 't_600', 't_500',
      't_400', 't_300', 't_250', 't_200', 't_150', 't_100', 't_50',

      # U wind (u)
      'u_1000', 'u_925', 'u_850', 'u_700', 'u_600', 'u_500',
      'u_400', 'u_300', 'u_250', 'u_200', 'u_150', 'u_100', 'u_50',

      # V wind (v)
      'v_1000', 'v_925', 'v_850', 'v_700', 'v_600', 'v_500',
      'v_400', 'v_300', 'v_250', 'v_200', 'v_150', 'v_100', 'v_50',

      # Ozone (o3)
      'o3_1000', 'o3_925', 'o3_850', 'o3_700', 'o3_600', 'o3_500',
      'o3_400', 'o3_300', 'o3_250', 'o3_200', 'o3_150', 'o3_100', 'o3_50',

      # Sulfur dioxide (so2)
      'so2_1000', 'so2_925', 'so2_850', 'so2_700', 'so2_600', 'so2_500',
      'so2_400', 'so2_300', 'so2_250', 'so2_200', 'so2_150', 'so2_100', 'so2_50',

      # Geopotential height (z)
      'z_1000', 'z_925', 'z_850', 'z_700', 'z_600', 'z_500',
      'z_400', 'z_250', 'z_200', 'z_150', 'z_100', 'z_50',
  ]
  loss_weight : 1.
  masking_rate : 0.6
  masking_rate_none : 0.05
  token_size : 32
  tokenize_spacetime : True
  embed : 
    net : transformer
    num_tokens : 1
    num_heads : 8
    dim_embed : 256
    num_blocks : 2
  embed_target_coords :
    net : linear
    dim_embed : 256 
  target_readout :
    type : 'obs_value'  # token or obs_value
    num_layers : 2
    num_heads : 4
    # sampling_rate : 0.2
  pred_head :
    ens_size : 1
    num_layers : 1