# (C) Copyright 2024 WeatherGenerator contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

RADKLIM:
  type: radklim
  name: RADKLIM
  filenames: ['radklim_full_dataset.json'] 
  reference: "/p/scratch/weatherai/data/npp-atms-unpacked/temp_radklim/radklim_output_kerchunk/radklim_full_dataset.json"
  stats_path: "/p/scratch/weatherai/data/npp-atms-unpacked/temp_radklim/radklim_output_kerchunk/dummy_radklim_stats.json"

  source_channels: ['RR']
  target_channels: ['RR']
  geoinfo_channels: []

  loss_weight: 1.0
  diagnostic: false
  masking_rate: 0.6
  masking_rate_none: 0.05
  token_size: 32

  embed:
    net: transformer
    num_tokens: 1
    num_heads: 8
    dim_embed: 512
    num_blocks: 2

  embed_target_coords:
    net: linear
    dim_embed: 512

  target_readout:
    type: obs_value
    num_layers: 2
    num_heads: 4
    # sampling_rate: 0.2

  pred_head:
    ens_size: 1
    num_layers: 1