# (C) Copyright 2024 WeatherGenerator contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

ERA5 :
  type : anemoi
  # filenames : ['aifs-ea-an-oper-0001-mars-o96-1979-2023-6h-v8.zarr']
  filenames : ['aifs-ea-an-oper-0001-mars-o48-1979-2024-6h-v1.zarr']
  source_exclude : ['w_', 'skt', 'tcw', 'cp', 'tp']
  target_exclude : ['w_', 'slor', 'sdor', 'tcw', 'cp', 'tp']
  loss_weight : 1.
  location_weight : cosine_latitude
  masking_rate : 0.6
  masking_rate_none : 0.05
  token_size : 8
  tokenize_spacetime : True
  max_num_targets: -1
  embed : 
    net : transformer
    num_tokens : 1
    num_heads : 8
    dim_embed : 256
    num_blocks : 2
  embed_target_coords :
    net : linear
    dim_embed : 256
  target_readout :
    type : 'obs_value'  # token or obs_value
    num_layers : 1
    num_heads : 4
    # sampling_rate : 0.2
  pred_head :
    ens_size : 1
    num_layers : 1
  channel_weights :
    q_50: 0.12
    q_100: 0.12
    q_150: 0.12
    q_200: 0.12
    q_250: 0.15
    q_300: 0.18
    q_400: 0.24
    q_500: 0.3
    q_600: 0.36
    q_700: 0.42
    q_850: 0.51
    q_925: 0.56
    q_1000: 0.6
    t_50: 1.2
    t_100: 1.2
    t_150: 1.2
    t_200: 1.2
    t_250: 1.5
    t_300: 1.8
    t_400: 2.4
    t_500: 3.0
    t_600: 3.6
    t_700: 4.2
    t_850: 5.1
    t_925: 5.55
    t_1000: 6.0
    u_50: 0.16
    u_100: 0.16
    u_150: 0.16
    u_200: 0.16
    u_250: 0.2
    u_300: 0.24
    u_400: 0.32
    u_500: 0.4
    u_600: 0.48
    u_700: 0.56
    u_850: 0.68
    u_925: 0.74
    u_1000: 0.8
    v_50: 0.1
    v_100: 0.1
    v_150: 0.1
    v_200: 0.1
    v_250: 0.12
    v_300: 0.15
    v_400: 0.2
    v_500: 0.25
    v_600: 0.3
    v_700: 0.35
    v_850: 0.42
    v_925: 0.46
    v_1000: 0.5
    z_50: 2.4
    z_100: 2.4
    z_150: 2.4
    z_200: 2.4
    z_250: 3.0
    z_300: 3.6
    z_400: 4.8
    z_500: 6.0
    z_600: 7.2
    z_700: 8.4
    z_850: 10.2
    z_925: 11.1
    z_1000: 12.0
    10u: 0.5
    10v: 0.5
    2d: 0.5
    2t: 1.0
    msl: 1.0
    skt: 1.0
    sp: 10.0
