# This YAML file controls which model runs are compared in utils/compare_run_configs.py.
# Specify run_ids and their model directories below.
# Use always_show_patterns to control which parameters are always shown in the output table.
# Put '*' to show all parameters, or leave empty to only show changed parameters.
# Use for example 'ae_global' to show all parameters starting with 'ae_global'.
run_ids:
  - [u4dtysia, /p/project1/hclimrep/polz1/code/WeatherGenerator/models]
  - [v7m5ofcl, /p/project1/hclimrep/polz1/code/WeatherGenerator/models]
  - [jpyzgvtw, /p/project1/hclimrep/polz1/code/WeatherGenerator/models]
always_show_patterns:
  - '*'