verbose: true
global_plotting_options:
 image_format : "png" #options: "png", "pdf", "svg", "eps", "jpg" ..
 dpi_val : 300

summary_plots : true
print_summary: false

evaluation:
  metrics  : ["rmse"]
  regions: ["global", "nhem"]
run_ids :
  wtqfk9i5:
    label: "CAMS EAC4 forecast epoch=25 dim_embed = 512 token_size = 16 num_blocks = 2"
    epoch: 0
    rank: 0
    streams:
      # ERA5:
      #   channels: ["2t", "10u", "10v", "z_500", "t_850", "u_850", "v_850", "q_850", ]
      #   evaluation:
      #     forecast_step: "all"
      #     sample: "all"
      #   plotting:
      #     sample: [0]
      #     forecast_step: [ 1, 2, 3, 4, 5, 6, 7, 8]
      #     plot_maps: true
      #     plot_histograms: true
      #     plot_animations: false
      CAMSEAC4: 
        channels: [
          # Surface variables
          'pm1', 'pm2p5', 'pm10',
          'tc_co', 'tc_no', 'tc_no2', 'tc_o3', 'tc_so2',

          # Ozone (o3)
          'go3_1000', 'go3_925', 'go3_850', 'go3_700', 'go3_600', 'go3_500',
          'go3_400', 'go3_300', 'go3_250', 'go3_200', 'go3_150', 'go3_100', 'go3_50',

          # Sulfur dioxide (so2)
          'so2_1000', 'so2_925', 'so2_850', 'so2_700', 'so2_600', 'so2_500',
          'so2_400', 'so2_300', 'so2_250', 'so2_200', 'so2_150', 'so2_100', 'so2_50',

          # Nitrogen monoxide (no)
          'no_1000', 'no_925', 'no_850', 'no_700', 'no_600', 'no_500',
          'no_400', 'no_300', 'no_250', 'no_200', 'no_150', 'no_100', 'no_50',

          # Nitrogen dioxide (no2)
          'no2_1000', 'no2_925', 'no2_850', 'no2_700', 'no2_600', 'no2_500',
          'no2_400', 'no2_300', 'no2_250', 'no2_200', 'no2_150', 'no2_100', 'no2_50',

          # Carbon monoxide (co)
          'co_1000', 'co_925', 'co_850', 'co_700', 'co_600', 'co_500',
          'co_400', 'co_300', 'co_250', 'co_200', 'co_150', 'co_100', 'co_50',
        ]
        evaluation:
          forecast_step: "all"
          sample: "all"
        plotting:
          sample: [0]
          forecast_step: [ 1, 2, 3, 4, 5, 6, 7, 8]
          plot_maps: true
          plot_histograms: true
          plot_animations: true
  # e8fzh2t1:
  #   label: "CAMS forecast finetune dim_embed = 256 token_size = 16 num_blocks = 2"
  #   epoch: 0
  #   rank: 0
  #   streams:
  #     # ERA5:
  #     #   channels: ["2t", "10u", "10v", "z_500", "t_850", "u_850", "v_850", "q_850", ]
  #     #   evaluation:
  #     #     forecast_step: "all"
  #     #     sample: "all"
  #     #   plotting:
  #     #     sample: [0]
  #     #     forecast_step: [ 1, 2, 3, 4, 5, 6, 7, 8]
  #     #     plot_maps: true
  #     #     plot_histograms: true
  #     #     plot_animations: false
  #     CAMSEAC4: 
  #       channels: [
  #         # Surface variables
  #         'pm1', 'pm2p5', 'pm10',
  #         'tc_co', 'tc_no', 'tc_no2', 'tc_o3', 'tc_so2',

  #         # Ozone (o3)
  #         'go3_1000', 'go3_500', 'go3_250','go3_50',

  #         # Sulfur dioxide (so2)
  #         'so2_1000', 'so2_500', 'so2_250','so2_50',


  #         # Nitrogen monoxide (no)
  #         'no_1000', 'no_500', 'no_250','no_50',

  #         # Nitrogen dioxide (no2)
  #         'no2_1000', 'no2_500', 'no2_250','no2_50',


  #         # Carbon monoxide (co)
  #         'co_1000', 'co_500', 'co_250','co_50',

  #       ]
  #       evaluation:
  #         forecast_step: "all"
  #         sample: "all"
  #       plotting:
  #         sample: [0]
  #         forecast_step: [ 1, 2, 3, 4, 5, 6, 7, 8]
  #         plot_maps: true
  #         plot_histograms: true
  #         plot_animations: true
  # z6aup4r1:
  #   label: "CAMS forecast finetune dim_embed = 512 token_size = 32 num_blocks = 2"
  #   epoch: 0
  #   rank: 0
  #   streams:
  #     # ERA5:
  #     #   channels: ["2t", "10u", "10v", "z_500", "t_850", "u_850", "v_850", "q_850", ]
  #     #   evaluation:
  #     #     forecast_step: "all"
  #     #     sample: "all"
  #     #   plotting:
  #     #     sample: [0]
  #     #     forecast_step: [ 1, 2, 3, 4, 5, 6, 7, 8]
  #     #     plot_maps: true
  #     #     plot_histograms: true
  #     #     plot_animations: false
  #     CAMSEAC4: 
  #       channels: [
  #         # Surface variables
  #         'pm1', 'pm2p5', 'pm10',
  #         'tc_co', 'tc_no', 'tc_no2', 'tc_o3', 'tc_so2',

  #         # Ozone (o3)
  #         'go3_1000', 'go3_500', 'go3_250','go3_50',

  #         # Sulfur dioxide (so2)
  #         'so2_1000', 'so2_500', 'so2_250','so2_50',


  #         # Nitrogen monoxide (no)
  #         'no_1000', 'no_500', 'no_250','no_50',

  #         # Nitrogen dioxide (no2)
  #         'no2_1000', 'no2_500', 'no2_250','no2_50',


  #         # Carbon monoxide (co)
  #         'co_1000', 'co_500', 'co_250','co_50',

  #       ]
  #       evaluation:
  #         forecast_step: "all"
  #         sample: "all"
  #       plotting:
  #         sample: [0]
  #         forecast_step: [ 1, 2, 3, 4, 5, 6, 7, 8]
  #         plot_maps: true
  #         plot_histograms: true
  #         plot_animations: true