verbose: true
image_format : "png" #options: "png", "pdf", "svg", "eps", "jpg" ..
dpi_val : 300
summary_plots : true
print_summary: false

evaluation:
  metrics  : ["rmse"]
  regions: ["global"]

run_ids :

  ptluswdo:
    label: "ptluswdo: 64ep 2fs (naoj54ch) + 32ep 8fs 2e-5"
    epoch: 0
    rank: 0
    streams:
      ERA5:
        channels: ["2t", "10u", "10v", "z_500", "t_850", "u_850", "v_850", "q_850", ]
        #channels: ["2t", "q_850", ]
        evaluation:
          sample: "all"
          forecast_step: "all"
        plotting:
          sample: [0]
          forecast_step: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
          plot_maps: true
          plot_histograms: false