streams_directory: "./config/streams/icon_esm_historical_day"

start_date: 185001011100
end_date:  200912311200
start_date_val: 201001011100 
end_date_val: 201912311200

multiprocessing_method: "spawn"

len_hrs: 24
step_hrs: 24

streams_output: ['ICONESMOday', 'ICONESMSIday', 'ICONESMday']
