streams_directory: "./config/streams/iconart_6h/"
start_date: 201902010000
end_date: 202111250000  # 4256 timesteps (divisible by 32 = 4 ranks × 8 workers × 1)
start_date_val: 202111250600
end_date_val: 202112310000  # 512 timesteps (divisible by 32)

analysis_streams_output: ["ICONART"]

forecast_offset : 1
forecast_delta_hrs: 0
forecast_steps: 4
forecast_policy: "fixed"
forecast_att_dense_rate: 1.0
fe_num_blocks: 8
fe_num_heads: 16
fe_dropout_rate: 0.1
num_epochs: 10