streams_directory: "./config/streams/streams_icon_cmip6"

start_date: 185001011100
end_date:  200912311200
start_date_val: 201001011100 
end_date_val: 201912311200

num_epochs: 200 # 10

# samples_per_epoch: 100 #  works # 100 works
# samples_per_validation: 100 
# shuffle: True

loader_num_workers: 16
masking_rate: 0.8
multiprocessing_method: "spawn"

# forecast_offset : 1 

len_hrs: 745
step_hrs: 24