streams_directory: "./config/streams/icon_esm_historical_mon"

start_date: 185001011100
end_date:  200912311200
start_date_val: 201001011100 
end_date_val: 201912311200


multiprocessing_method: "spawn"

len_hrs: 745
step_hrs: 745

streams_output: ['ICONESMAERmon', 'ICONESMAmon', 'ICONESMEmon', 'ICONESMLImon',
  'ICONESMLImon', 'ICONESMOmon', 'ICONESMSImon']