streams_directory: "./config/streams/streams_ocean/"

ae_local_num_queries: 2
ae_adapter_embed: 128
ae_local_dim_embed: 1024
ae_local_num_blocks: 4
ae_local_num_heads: 16

start_date: 20001010000
end_date: 219912310000
start_date_val: 220001010000
end_date_val: 222012310000

num_epochs: 111
samples_per_epoch: 16392
samples_per_validation: 1024
shuffle: True
loader_num_workers: 4

lr_max: 2e-5
