verbose: true
results_dir : "./results/"
output_plotting_dir: "./plots/"
output_scores_dir : "./jsons/"
image_format : "png" #options: "png", "pdf", "svg", "eps", "jpg" ..
dpi_val : 300
summary_plots : true

evaluation:
  metrics  : ["rmse", "l1", "mse"]

#MTM models
model_ids :
  wz9rbl3w:
     streams:
       ERA5:
         channels: ["2t", "10u", "z_500"]
         evaluation:
           forecast_step: "all"
           sample: "all"
         plotting: 
           sample: [1, 2, 3]
           forecast_step: [0]
           plot_maps: true
           plot_histograms: false
     label: "MTM ERA5"
     epoch: 0
     rank: 0
    
  vy2d4be7:
    label: "forecast ERA5"
    epoch: 0
    rank: 0
    streams:
      ERA5:
        channels: ["2t", "10u"]
        evaluation:
          forecast_step: "all"
          sample: "all"
        plotting: 
          sample: [0]
          forecast_step: [0, 2]
          plot_maps: false
          plot_histograms: false 
      NPPATMS:
        channels: ["obsvalue_rawbt_1", "obsvalue_rawbt_5"]
        evaluation: 
          forecast_step: "all"
          sample: "all"
        plotting: 
          forecast_step: [1, 2]
          sample: [0]
          plot_maps: true
          plot_histograms: false
      
