verbose: true
results_dir : "./results/"
output_plotting_dir: "./plots/"
output_scores_dir : "./jsons/"
image_format : "png" #options: "png", "pdf", "svg", "eps", "jpg" ..
dpi_val : 300
summary_plots : true
print_summary: false #print out score values on screen. it can be verbose

evaluation:
  metrics  : ["rmse", "acc"]

run_ids :
  fqgok8t9:
    label: "forecast ERA5"
    epoch: 0
    rank: 0
    streams:
      ERA5:
        channels: ["2t", "10u", "10v", "z_500", "q_850", "t_850", "u_850", "v_850"]
        evaluation:
          forecast_step: "all"
          sample: "all"
        plotting: 
          sample: [0]
          forecast_step: [1, 2]
          plot_maps: true
          plot_histograms: false 