train : 
  plot :
    # random masking
    #v9mbu064_ft : 
    #  slurm_id: 0
    #  description: "ft, random, 0.2"
    #dgztdko9_ft : 
    #  slurm_id: 0
    #  description: "ft, random, 0.8"
    # healpix masking
    #ocgmx23u_ft : 
    #  slurm_id: 0
    #  description: "ft, healpix, 0.2, hl_level 3"
    #xjz5bsw6_ft : 
    #  slurm_id: 0
    #  description: "ft, healpix, 0.4, hl_level 3"
    c534btp8_ft : 
      slurm_id: 0
      description: "ft, healpix, 0.6, hl_level 3"
    #dlctmqor_ft : 
    #  slurm_id: 0
    #  description: "ft, healpix, 0.8, hl_level 3"
    #o4dmnf5z_ft : 
    #  slurm_id: 0
    #  description: "ft, healpix, 0.2, hl_level 1"
    #i50ua7oz_ft : 
    #  slurm_id: 0
    #  description: "ft, healpix, 0.4, hl_level 1"
    #rrf3mew2_ft : 
    #  slurm_id: 0
    #  description: "ft, healpix, 0.6, hl_level 1"
    #f9175xus_ft : 
    #  slurm_id: 0
    #  description: "ft, healpix, 0.8, hl_level 1"
    # channel masking
    #grwmyvg7_ft : 
    #  slurm_id: 0
    #  description: "ft, channel, 0.2, global"
    #fmcskew0_ft : 
    #  slurm_id: 0
    #  description: "ft, channel, 0.4, global"
    #ig31dlum_ft : 
    #  slurm_id: 0
    #  description: "ft, channel, 0.6, global"
    #j78nhv4r_ft : 
    #  slurm_id: 0
    #  description: "ft, channel, 0.8, global"
    #g4ts9lie_ft : 
    #  slurm_id: 0
    #  description: "ft, channel, 0.2, per_cell"
    #oj56x4nq_ft : 
    #  slurm_id: 0
    #  description: "ft, channel, 0.4, per_cell"
    #vzsl502k_ft : 
    #  slurm_id: 0
    #  description: "ft, channel, 0.6, per_cell"
    y1mplb38_ft : 
      slurm_id: 0
      description: "ft, channel, 0.8, per_cell"

