[project]
name = "weathergen-evaluation"
version = "0.1.0"
description = "Evaluation package of the WeatherGenerator project"
#readme = "README.md"
requires-python = ">=3.11,<3.13"

dependencies = [
 'pandas',
 'matplotlib',
 "polars",
]

[dependency-groups]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/weathergen"]