# (C) Copyright 2024 WeatherGenerator contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

ICONCMIP6Amon :
  type : iconcmip6
  filenames : ['1pctCO2_r1i1p1f1_Amon.json']
  attributes:
    lon: 'longitude'
    lat: 'latitude'
    grid: 'i' # i = grid indexes
  # source_exclude: [
  #   "hur", # bcause it doesn't have data on all necessary levels
  #   'clt',   'hfss', 'pr',   'rlds',  'rlut',  'rsus',  'tas',  'vas', # duplicate from day
  #   'hfls', 'psl',  'rlus',  'rsds',  'sfcWind',  'uas'  # duplicate from day 
  # ]
  # target_exclude: [
  #   "hur", # bcause it doesn't have data on all necessary levels
  #   'clt',   'hfss', 'pr',   'rlds',  'rlut',  'rsus',  'tas',  'vas', # duplicate from day
  #   'hfls', 'psl',  'rlus',  'rsds',  'sfcWind',  'uas'   # duplicate from day
  # ]
  source_exclude: [ #clivi # ua
    "clwvi", "hfls", "hur", "pr", "prsn", "ps", "rlds", "rlus", "rlutcs", "rsdscs", "rsus", "rsut", 
    "rtmt", "ta", "tauu", "ts", "uas", "vas", "zg", "clt", "evspsbl", "hfss", "hus", "prc", "prw", 
    "psl", "rldscs", "rlut", "rsds", "rsdt", "rsuscs", "rsutcs", "sfcWind", "tas", "tauv", "va", "wap"
  ]
  target_exclude: [ #clivi # ua
    "clwvi", "hfls", "hur", "pr", "prsn", "ps", "rlds", "rlus", "rlutcs", "rsdscs", "rsus", "rsut", 
    "rtmt", "ta", "tauu", "ts", "uas", "vas", "zg", "clt", "evspsbl", "hfss", "hus", "prc", "prw", 
    "psl", "rldscs", "rlut", "rsds", "rsdt", "rsuscs", "rsutcs", "sfcWind", "tas", "tauv", "va", "wap"
  ]
  pressure_levels: [
    "5000", "10000", "15000", "20000", "25000", "30000", 
    "40000", "50000", "60000", "70000", "85000", "92500", "100000"
  ]
  variables: [
    "clivi", "clwvi", "hfls", "hur", "pr", "prsn", "ps", "rlds", "rlus", "rlutcs", "rsdscs", "rsus", "rsut", 
    "rtmt", "ta", "tauu", "ts", "uas", "vas", "zg", "clt", "evspsbl", "hfss", "hus", "prc", "prw", 
    "psl", "rldscs", "rlut", "rsds", "rsdt", "rsuscs", "rsutcs", "sfcWind", "tas", "tauv", "ua", "va", "wap"
  ]
  loss_weight : 1.
  diagnostic : False
  masking_rate : 0.6
  masking_rate_none : 0.05
  token_size : 8
  embed : 
    net : transformer
    num_tokens : 1
    num_heads : 8
    dim_embed : 256
    num_blocks : 2
  embed_target_coords :
    net : linear
    dim_embed : 256
  target_readout :
    type : 'obs_value'  # token or obs_value
    num_layers : 2
    num_heads : 4
    # sampling_rate : 0.2
  pred_head :
    ens_size : 1
    num_layers : 1