name: Main workflow


jobs:
  linting:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.6.2"

      - name: Set up Python
        run: uv python install

      - name: Run black
        run: uv run black --check src/wegen_utils     

      - name: Run ruff (flake8)
        run: uv run ruff src/wegen_utils