name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop", "feature/*" ]
    paths-ignore:
      - "CHANGELOG.md"
      - "README.md"

jobs:
  linting:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.6.2"

      - name: Run ruff (black)
        # Do not attempt to install the default dependencies
        run: uv run --no-default-groups --group lint ruff format --check -n src/wegen_utils

      - name: Run ruff (flake8)
        # Do not attempt to install the default dependencies
        run: uv run --no-default-groups --group lint ruff check src/wegen_utils